SQL> select player_name 선수이름, position 포지션, back_no 백넘버, height 키
  2  from player
  3  where (team_id = 'K02' or team_id = 'K07')
  4  and position = 'MF'
  5  and height >= 170
  6  and height <= 180;

SQL> select player_name 선수이름, position 포지션, back_no 백넘버, height 키
  2  from player
  3  where team_id in ('K02', 'K07')
  4  and position = 'MF'
  5  and height between 170 and 180;

SQL> select ename, job, deptno
  2  from emp
  3  where (job, deptno) in (('MANAGER', 20), ('CLERK', 30));

SQL> SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE PLAYER_NAME LIKE '장%';



SQL> SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE PLAYER_NAME LIKE '_F%';

SQL> SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE POSITION = NULL;

SQL> SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE POSITION IS NULL;

SQL> SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02'
  4  AND NOT POSITION = 'MF'
  5  AND NOT HEIGHT BETWEEN 175 AND 185;

SQL> SELECT PLAYER_NAME 선수이름, NATION 국적
  2  FROM PLAYER
  3  WHERE NATION IS NOT NULL;

SQL> SELECT SYSDATE FROM DUAL;

SQL> SELECT ENAME, HIREDATE,
  2  EXTRACT(YEAR FROM HIREDATE) 입사년도,
  3  EXTRACT(MONTH FROM HIREDATE) 입사월,
  4  EXTRACT(DAY FROM HIREDATE) 입사일
  5  FROM EMP;

SQL> SELECT ENAME, HIREDATE,
  2  TO_NUMBER(TO_CHAR(HIREDATE, 'YYYY')) 입사년도,
  3  TO_NUMBER(TO_CHAR(HIREDATE, 'MM')) 입사월,
  4  TO_NUMBER(TO_CHAR(HIREDATE, 'DD')) 입사일
  5  FROM EMP;

SQL> SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD') 숫자,
  2  TO_CHAR(SYSDATE, 'YYYY. MON, DAY') 문자
  3  FROM DUAL;

SQL> SELECT TO_CHAR(123456789/1200, '$999,999,999.99') 환율반영달러,
  2  TO_CHAR(123456789, 'L999,999,999') 원화
  3  FROM DUAL;

SQL> SELECT LOC,
  2  CASE LOC
  3  WHEN 'NEW YORK' THEN 'EAST'
  4  WHEN 'BOSTON' THEN 'EAST'
  5  WHEN 'CHICAGO' THEN 'CENTER'
  6  WHEN 'DALLAS' THEN 'CENTER'
  7  ELSE 'ETC'
  8  END as AREA
  9  FROM DEPT;

SQL> SELECT ENAME,
  2  CASE WHEN SAL >= 3000 THEN 'HIGH'
  3  WHEN SAL >= 1000 THEN 'MID'
  4  ELSE 'LOW'
  5  END AS SALARY_GRADE
  6  FROM EMP;

SQL> SELECT ENAME, SAL,
  2  CASE WHEN SAL >= 2000
  3  THEN 1000
  4  ELSE (CASE WHEN SAL >= 1000
  5  THEN 500
  6  ELSE 0
  7  END)
  8  END as BONUS
  9  FROM EMP;

SQL> SELECT PLAYER_NAME 선수명, POSITION,
  2  NVL(POSITION, '없음') 포지션
  3  FROM PLAYER
  4  WHERE TEAM_ID = 'K08';

SQL> SELECT PLAYER_NAME 선수명, POSITION,
  2  CASE WHEN POSITION IS NULL
  3  THEN '없음'
  4  ELSE POSITION
  5  END as 포지션
  6  FROM PLAYER
  7  WHERE TEAM_ID = 'K08';

SQL> SELECT MGR FROM EMP
  2  WHERE ENAME='KING';

SQL> SELECT NVL(MGR, 9999) MGR FROM EMP WHERE ENAME='JSC';

SQL> SELECT NVL(MAX(MGR), 9999) MGR FROM EMP
  2  WHERE ENAME='JSC';

SQL> SELECT ENAME, EMPNO, MGR, NULLIF(MGR, 7698) NUIF
  2  FROM EMP;

SQL> SELECT ENAME, EMPNO, MGR,
  2  CASE WHEN MGR = 7698
  3  THEN NULL
  4  ELSE MGR
  5  END NUIF
  6  FROM EMP;

SQL> SELECT ENAME, COMM, SAL, COALESCE(COMM, SAL) COAL
  2  FROM EMP;

SQL> SELECT ENAME, COMM, SAL,
  2  CASE WHEN COMM IS NOT NULL
  3  THEN COMM
  4  ELSE (CASE WHEN SAL IS NOT NULL
  5  THEN SAL
  6  ELSE NULL
  7  END)
  8  END COAL
  9  FROM EMP;



