SQL> SELECT COUNT(*) "전체 행수", COUNT(HEIGHT) "키 건수",
  2  MAX(HEIGHT) 최대키, MIN(HEIGHT) 최소키, ROUND(AVG(HEIGHT), 2) 평균키
  3  FROM PLAYER;

SQL> SELECT POSITION 포지션, COUNT(*) 인원수, COUNT(HEIGHT) 키대상,
  2  MAX(HEIGHT) 최대키, MIN(HEIGHT) 최소키, ROUND(AVG(HEIGHT), 2) 평균키
  3  FROM PLAYER
  4  GROUP BY POSITION;

SQL> SELECT POSITION 포지션, ROUND(AVG(HEIGHT), 2) 평균키
  2  FROM PLAYER
  3  GROUP BY POSITION
  4  HAVING AVG(HEIGHT) >= 180;

SQL> SELECT POSITION 포지션, ROUND(AVG(HEIGHT), 2) 평균키
  2  FROM PLAYER
  3  GROUP BY POSITION
  4  HAVING MAX(HEIGHT) >= 190;


SQL> SELECT ENAME, DEPTNO, EXTRACT(MONTH FROM HIREDATE) 입사월, SAL
  2  FROM EMP;

SQL> SELECT DEPTNO,
  2  AVG(CASE MONTH WHEN 1 THEN SAL END) MO1,
  3  AVG(CASE MONTH WHEN 2 THEN SAL END) MO2,
  4  AVG(CASE MONTH WHEN 3 THEN SAL END) MO3,
  5  AVG(CASE MONTH WHEN 4 THEN SAL END) MO4,
  6  AVG(CASE MONTH WHEN 5 THEN SAL END) MO5,
  7  AVG(CASE MONTH WHEN 6 THEN SAL END) MO6,
  8  AVG(CASE MONTH WHEN 7 THEN SAL END) MO7,
  9  AVG(CASE MONTH WHEN 8 THEN SAL END) MO8,
 10  AVG(CASE MONTH WHEN 9 THEN SAL END) MO9,
 11  AVG(CASE MONTH WHEN 10 THEN SAL END) M10,
 12  AVG(CASE MONTH WHEN 11 THEN SAL END) M11,
 13  AVG(CASE MONTH WHEN 12 THEN SAL END) M12
 14  FROM (SELECT ENAME, DEPTNO, EXTRACT(MONTH FROM HIREDATE) MONTH, SAL
 15  FROM EMP)
 16  GROUP BY DEPTNO;

SQL> SELECT DEPTNO,
  2  AVG(DECODE(MONTH, 1, SAL)) MO1, AVG(DECODE(MONTH, 2, SAL)) MO2,
  3  AVG(DECODE(MONTH, 3, SAL)) MO3, AVG(DECODE(MONTH, 4, SAL)) MO4,
  4  AVG(DECODE(MONTH, 5, SAL)) MO5, AVG(DECODE(MONTH, 6, SAL)) MO6,
  5  AVG(DECODE(MONTH, 7, SAL)) MO7, AVG(DECODE(MONTH, 8, SAL)) MO8,
  6  AVG(DECODE(MONTH, 9, SAL)) MO9, AVG(DECODE(MONTH, 10, SAL)) M10,
  7  AVG(DECODE(MONTH, 11, SAL)) M11, AVG(DECODE(MONTH, 12, SAL)) M12
  8  FROM (SELECT ENAME, DEPTNO, EXTRACT(MONTH FROM HIREDATE) MONTH, SAL
  9  FROM EMP)
 10  GROUP BY DEPTNO;

SQL> SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE HEIGHT IS NOT NULL
  4  ORDER BY HEIGHT DESC, BACK_NO ASC;

SQL> SELECT DNAME, LOC, DEPTNO
  2  FROM DEPT
  3  ORDER BY DNAME ASC, LOC ASC,
  4  DEPTNO DESC;

SQL> SELECT DNAME DEPT, LOC AREA, DEPTNO
  2  FROM DEPT
  3  ORDER BY DNAME, AREA, DEPTNO DESC;

SQL> SELECT DNAME, LOC, DEPTNO
  2  FROM DEPT
  3  ORDER BY DNAME, LOC, DEPTNO DESC;

SQL> SELECT DNAME, LOC as AREA, DEPTNO
  2  FROM DEPT
  3  ORDER BY 1, AREA, 3 DESC;

SQL> SELECT EMPNO, ENAME
  2  FROM EMP
  3  ORDER BY MGR;

SQL> SELECT EMPNO FROM
  2  (SELECT EMPNO, ENAME FROM EMP ORDER BY MGR);

SQL> SELECT MRG FROM
  2  (SELECT EMPNO, ENAME FROM EMP ORDER BY MGR);
//오류 미정의된 칼럼

SQL> SELECT JOB, DEPTNO
  2  FROM EMP
  3  GROUP BY JOB
  4  HAVING COUNT(*) > 0
  5  ORDER BY SAL;
//SELECT DEPTNO 때문에 오류 발생

SQL> SELECT JOB
  2  FROM EMP
  3  GROUP BY JOB
  4  HAVING COUNT(*) > 0
  5  ORDER BY SAL;
//ORDERBY SAL 때문에 오류 발생

SQL> SELECT JOB
  2  FROM EMP
  3  GROUP BY JOB
  4  HAVING COUNT(*) > 0
  5  ORDER BY MAX(EMPNO), MAX(MGR), SUM(SAL), COUNT(DEPTNO), MAX(HIREDATE);

SQL> SELECT ENAME, SAL
  2  FROM EMP
  3  WHERE ROWNUM < 4
  4  ORDER BY SAL DESC;
//추출 후 정렬

SQL> SELECT ENAME, SAL
  2  FROM (SELECT ENAME, SAL
  3  FROM EMP
  4  ORDER BY SAL DESC)
  5  WHERE ROWNUM < 4;
//정렬 후 추출

SQL> SELECT PLAYER.PLAYER_NAME, PLAYER.BACK_NO, PLAYER.TEAM_ID,
  2  TEAM.TEAM_NAME, TEAM.REGION_NAME
  3  FROM PLAYER, TEAM
  4  WHERE PLAYER.TEAM_ID = TEAM.TEAM_ID;

SQL> SELECT P.PLAYER_NAME 선수명, P.BACK_NO 백넘버, P.TEAM_ID 팀코드,
  2  T.TEAM_NAME 팀명, T.REGION_NAME 연고지
  3  FROM PLAYER P, TEAM T
  4  WHERE P.TEAM_ID = T.TEAM_ID;

SQL> SELECT P.PLAYER_NAME 선수명, P.BACK_NO 백넘버,
  2  T.TEAM_NAME 팀명, T.REGION_NAME 연고지
  3  FROM PLAYER P, TEAM T
  4  WHERE P.TEAM_ID = T.TEAM_ID
  5  AND P.POSITION = 'GK'
  6  ORDER BY P.BACK_NO;

SQL> SELECT TEAM.REGION_NAME, TEAM.TEAM_NAME, TEAM.STADIUM_ID,
  2  STADIUM.STADIUM_NAME, STADIUM.SEAT_COUNT
  3  FROM TEAM, STADIUM
  4  WHERE TEAM.STADIUM_ID = STADIUM.STADIUM_ID;

SQL> SELECT T.REGION_NAME, T.TEAM_NAME, T.STADIUM_ID,
  2  S.STADIUM_NAME, S.SEAT_COUNT
  3  FROM TEAM T, STADIUM S
  4  WHERE T.STADIUM_ID = S.STADIUM_ID;

SQL> SELECT REGION_NAME, TEAM_NAME, T.STADIUM_ID,
  2  STADIUM_NAME, SEAT_COUNT
  3  FROM TEAM T, STADIUM S
  4  WHERE T.STADIUM_ID  = S.STADIUM_ID;

SQL> SELECT P.PLAYER_NAME 선수명, P.POSITION 포지션,
  2  T.REGION_NAME 연고지, T.TEAM_NAME 팀명,
  3  S.STADIUM_NAME 구장명
  4  FROM PLAYER P, TEAM T, STADIUM S
  5  WHERE P.TEAM_ID = T.TEAM_ID
  6  AND T.STADIUM_ID = S.STADIUM_ID
  7  ORDER BY 선수명;

SQL> SELECT E.ENAME 사원명, E.SAL 급여, S.GRADE 급여등급
  2  FROM EMP E, SALGRADE S
  3  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;