
SQL> SELECT PLAYER.PLAYER_NAME, PLAYER.BACK_NO, PLAYER.TEAM_ID,
  2  TEAM.TEAM_NAME, TEAM.REGION_NAME
  3  FROM PLAYER, TEAM
  4  WHERE PLAYER.TEAM_ID = TEAM.TEAM_ID;

SQL> SELECT P.PLAYER_NAME 선수명, P.BACK_NO 백넘버, P.TEAM_ID 팀코드,
  2  T.TEAM_NAME 팀명, T.REGION_NAME 연고지
  3  FROM PLAYER P, TEAM T
  4  WHERE P.TEAM_ID = T.TEAM_ID;

SQL> SELECT P.PLAYER_NAME 선수명, P.BACK_NO 백넘버,
  2  T.TEAM_NAME 팀명, T.REGION_NAME 연고지
  3  FROM PLAYER P, TEAM T
  4  WHERE P.TEAM_ID = T.TEAM_ID
  5  AND P.POSITION = 'GK'
  6  ORDER BY P.BACK_NO;

SQL> SELECT TEAM.REGION_NAME, TEAM.TEAM_NAME, TEAM.STADIUM_ID,
  2  STADIUM.STADIUM_NAME, STADIUM.SEAT_COUNT
  3  FROM TEAM, STADIUM
  4  WHERE TEAM.STADIUM_ID = STADIUM.STADIUM_ID;

SQL> SELECT T.REGION_NAME, T.TEAM_NAME, T.STADIUM_ID,
  2  S.STADIUM_NAME, S.SEAT_COUNT
  3  FROM TEAM T, STADIUM S
  4  WHERE T.STADIUM_ID = S.STADIUM_ID;

SQL> SELECT REGION_NAME, TEAM_NAME, T.STADIUM_ID,
  2  STADIUM_NAME, SEAT_COUNT
  3  FROM TEAM T, STADIUM S
  4  WHERE T.STADIUM_ID  = S.STADIUM_ID;

SQL> SELECT P.PLAYER_NAME 선수명, P.POSITION 포지션,
  2  T.REGION_NAME 연고지, T.TEAM_NAME 팀명,
  3  S.STADIUM_NAME 구장명
  4  FROM PLAYER P, TEAM T, STADIUM S
  5  WHERE P.TEAM_ID = T.TEAM_ID
  6  AND T.STADIUM_ID = S.STADIUM_ID
  7  ORDER BY 선수명;

SQL> SELECT E.ENAME 사원명, E.SAL 급여, S.GRADE 급여등급
  2  FROM EMP E, SALGRADE S
  3  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SQL> SELECT EMP.DEPTNO, EMPNO, ENAME, DNAME
  2  FROM EMP, DEPT
  3  WHERE EMP.DEPTNO = DEPT.DEPTNO;

SQL> SELECT EMP.DEPTNO, EMPNO, ENAME, DNAME
  2  FROM EMP INNER JOIN DEPT
  3  ON EMP.DEPTNO = DEPT.DEPTNO;

SQL> SELECT EMP.DEPTNO, EMPNO, ENAME, DNAME
  2  FROM EMP JOIN DEPT
  3  ON EMP.DEPTNO = DEPT.DEPTNO;

SQL> SELECT DEPTNO, EMPNO, ENAME, DNAME
  2  FROM EMP NATURAL JOIN DEPT;

SQL> SELECT DEPTNO, DNAME, DEPT.LOC
  2  FROM DEPT JOIN DEPT_TEMP
  3  USING (DEPTNO, DNAME);

SQL> SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME
  2  FROM EMP E JOIN DEPT D
  3  ON (E.DEPTNO = D.DEPTNO);

SQL> SELECT E.ENAME, E.DEPTNO, D.DEPTNO, D.DNAME
  2  FROM EMP E JOIN DEPT D
  3  ON (E.DEPTNO = D.DEPTNO)
  4  WHERE E.DEPTNO = 30;

SQL> SELECT TEAM_NAME, TEAM.STADIUM_ID, STADIUM_NAME
  2  FROM TEAM JOIN STADIUM
  3  ON TEAM.STADIUM_ID = STADIUM.STADIUM_ID
  4  ORDER BY STADIUM_ID;

SQL> SELECT TEAM_NAME, STADIUM_ID, STADIUM_NAME
  2  FROM TEAM JOIN STADIUM
  3  USING (STADIUM_ID)
  4  ORDER BY STADIUM_ID;

SQL> SELECT TEAM_NAME, TEAM.STADIUM_ID, STADIUM_NAME
  2  FROM TEAM, STADIUM
  3  WHERE TEAM.STADIUM_ID = STADIUM.STADIUM_ID
  4  ORDER BY STADIUM_ID;

SQL> SELECT TEAM_NAME, TEAM_ID, STADIUM_NAME
  2  FROM TEAM JOIN STADIUM
  3  ON TEAM.TEAM_ID = STADIUM.HOMETEAM_ID
  4  ORDER BY TEAM_ID;

SQL> SELECT TEAM_NAME, TEAM_ID, STADIUM_NAME
  2  FROM TEAM, STADIUM
  3  WHERE TEAM.TEAM_ID = STADIUM.HOMETEAM_ID
  4  ORDER BY TEAM_ID;

SQL> SELECT P.PLAYER_NAME 선수명, P.POSITION 포지션, T.REGION_NAME 연고지명,
  2  T.TEAM_NAME 팀명, S.STADIUM_NAME 구장명
  3  FROM PLAYER P JOIN TEAM T
  4  ON P.TEAM_ID = T.TEAM_ID
  5  JOIN STADIUM S
  6  ON T.STADIUM_ID = S.STADIUM_ID
  7  WHERE P.POSITION = 'GK'
  8  ORDER BY 선수명;

SQL> SELECT P.PLAYER_NAME 선수명, P.POSITION 포지션, T.REGION_NAME 연고지명,
  2  T.TEAM_NAME 팀명, S.STADIUM_NAME 구장명
  3  FROM PLAYER P, TEAM T, STADIUM S
  4  WHERE P.TEAM_ID = T.TEAM_ID
  5  AND T.STADIUM_ID = S.STADIUM_ID
  6  AND P.POSITION = 'GK'
  7  ORDER BY 선수명;

SQL> SELECT ENAME, DNAME
  2  FROM EMP CROSS JOIN DEPT
  3  ORDER BY ENAME;