SQL> SELECT STADIUM_NAME, STADIUM.STADIUM_ID, SEAT_COUNT, HOMETEAM_ID, TEAM_NAME
  2  FROM STADIUM LEFT OUTER JOIN TEAM
  3  ON STADIUM.HOMETEAM_ID = TEAM.TEAM_ID
  4  ORDER BY HOMETEAM_ID;

SQL> SELECT E.ENAME, D.DEPTNO, D.DNAME
  2  FROM EMP E RIGHT OUTER JOIN DEPT D
  3  ON E.DEPTNO = D.DEPTNO;

SQL> SELECT *
  2  FROM DEPT FULL OUTER JOIN DEPT_TEMP
  3  ON DEPT.DEPTNO = DEPT_TEMP.DEPTNO;

SQL> SELECT PLAYER_NAME 선수명, BACK_NO 백넘버
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02'
  4  UNION ALL
  5  SELECT PLAYER_NAME 선수명, BACK_NO 백넘버
  6  FROM PLAYER
  7  WHERE TEAM_ID = 'K07'
  8  ORDER BY 1;

SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02'
  4  UNION ALL
  5  SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  6  FROM PLAYER
  7  WHERE TEAM_ID = 'KO7';


SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02' OR TEAM_ID = 'K07';

SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID IN ('K02', 'K07');

SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02'
  4  UNION
  5  SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  6  FROM PLAYER
  7  WHERE POSITION = 'GK';

SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02'
  4  UNION ALL
  5  SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  6  FROM PLAYER
  7  WHERE POSITION = 'GK';

SQL> SELECT 'P' 구분코드, POSITION 포지션, AVG(HEIGHT) 평균키
  2  FROM PLAYER
  3  GROUP BY POSITION
  4  UNION ALL
  5  SELECT 'T' 구분코드, TEAM_ID 팀명, AVG(HEIGHT) 평균키
  6  FROM PLAYER
  7  GROUP BY TEAM_ID
  8  ORDER BY 1, 2;

SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02'
  4  INTERSECT
  5  SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  6  FROM PLAYER
  7  WHERE POSITION = 'GK';  

SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02'
  4  AND PLAYER_ID IN (SELECT PLAYER_ID FROM PLAYER WHERE POSITION = 'GK');

SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER X
  3  WHERE X.TEAM_ID = 'K02'
  4  AND EXISTS (SELECT 1 FROM PLAYER Y
  5  WHERE Y.PLAYER_ID = X.PLAYER_ID
  6  AND Y.POSITION = 'GK');

SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02'
  4  MINUS
  5  SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  6  FROM PLAYER
  7  WHERE POSITION = 'MF';

SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02' AND POSITION <> 'MF';

SQL> SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
  2  FROM PLAYER
  3  WHERE TEAM_ID = 'K02'
  4  AND PLAYER_ID NOT IN (SELECT PLAYER_ID FROM PLAYER
  5  WHERE POSITION = 'MF');

SQL> SELECT LEVEL, LPAD('', 4*(LEVEL-1)) || EMPNO 사원, MGR 관리자,
  2  CONNECT_BY_ISLEAF ISLEAF
  3  FROM EMP
  4  START WITH MGR IS NULL
  5  CONNECT BY PRIOR EMPNO = MGR;

SQL> SELECT CONNECT_BY_ROOT EMPNO 시작사원, SYS_CONNECT_BY_PATH(EMPNO, '/') 경로,
  2  EMPNO 사원, MGR 관리자
  3  FROM EMP
  4  START WITH MGR IS NULL
  5  CONNECT BY PRIOR EMPNO = MGR;

SQL> SELECT LEVEL, LPAD('', 4 * (LEVEL-1)) || EMPNO 사원, MGR 관리자,
  2  CONNECT_BY_ISLEAF ISLEAF
  3  FROM EMP
  4  START WITH EMPNO = 'D'
  5  CONNECT BY PRIOR MGR = EMPNO;





